export const SET_ABOUTME_DATA = 'SET_ABOUTME_DATA';
export const SET_TAGLINE = "SET_TAGLINE";
export const SET_GLANCE_ITEMS = "SET_GLANCE_ITEMS";
export const SET_PROJECT_NAV_LIST = "SET_PROJECT_NAV_LIST";
export const SET_PROJECTS = "SET_PROJECTS";
